[ 2025-06-14 21:50:50,227 ] 19 networksecurity.logging.logger - INFO - Initiate the data ingestion
[ 2025-06-14 21:50:53,780 ] 65 root - INFO - Performed train test split on the dataframe
[ 2025-06-14 21:50:53,780 ] 67 root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[ 2025-06-14 21:50:53,781 ] 75 root - INFO - Exporting train and test file path.
[ 2025-06-14 21:50:53,915 ] 84 root - INFO - Exported train and test file path.
[ 2025-06-14 21:50:53,925 ] 25 networksecurity.logging.logger - INFO - Initiate the data Validation
[ 2025-06-14 21:50:54,060 ] 32 root - INFO - Required number of columns:2
[ 2025-06-14 21:50:54,061 ] 33 root - INFO - Data frame has columns:31
[ 2025-06-14 21:50:54,061 ] 32 root - INFO - Required number of columns:2
[ 2025-06-14 21:50:54,061 ] 33 root - INFO - Data frame has columns:31
[ 2025-06-14 21:50:54,298 ] 27 networksecurity.logging.logger - INFO - data Validation Completed
[ 2025-06-14 21:50:54,298 ] 31 networksecurity.logging.logger - INFO - data Transformation started
[ 2025-06-14 21:50:54,298 ] 63 root - INFO - Entered initiate_data_transformation method of DataTransformation class
[ 2025-06-14 21:50:54,298 ] 65 root - INFO - Starting data transformation
[ 2025-06-14 21:50:54,358 ] 48 root - INFO - Entered get_data_trnasformer_object method of Trnasformation class
[ 2025-06-14 21:50:54,358 ] 53 root - INFO - Initialise KNNImputer with {'missing_values': nan, 'n_neighbors': 3, 'weights': 'uniform'}
[ 2025-06-14 21:50:54,375 ] 46 root - INFO - Entered the save_object method of MainUtils class
[ 2025-06-14 21:50:54,379 ] 50 root - INFO - Exited the save_object method of MainUtils class
[ 2025-06-14 21:50:54,379 ] 46 root - INFO - Entered the save_object method of MainUtils class
[ 2025-06-14 21:50:54,383 ] 50 root - INFO - Exited the save_object method of MainUtils class
[ 2025-06-14 21:50:54,385 ] 35 networksecurity.logging.logger - INFO - data Transformation completed
[ 2025-06-14 21:50:54,385 ] 37 networksecurity.logging.logger - INFO - Model Training sstared
[ 2025-06-14 21:57:00,635 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022137077970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2025-06-14 21:57:06,766 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022137076BF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2025-06-14 21:57:17,736 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002213B0984F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2025-06-14 21:57:35,809 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002213B098610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2025-06-14 21:58:09,960 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022137077430>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2025-06-14 21:59:16,401 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022137076B90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2025-06-14 22:01:18,483 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221370768C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
